version: "3.4"

services:
  database:
    ports:
      - $DATABASE_PORT:$DATABASE_PORT
  application:
    entrypoint: ["java", "-agentlib:jdwp=transport=dt_socket,address=$DEBUG_PORT,suspend=n,server=y", "-jar", "/opt/payara/payara-micro.jar"]
    command: ["--deploymentDir", "/opt/payara/deployments"]
    ports:
      - $APPLICATION_PORT:$APPLICATION_PORT
      - $DEBUG_PORT:$DEBUG_PORT
